// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw0qpSAGCrEqpNdYBxtuxr0wwLqKcIfLY',
    appId: '1:941962863086:web:5fc93a5d44ca13aa92aeff',
    messagingSenderId: '941962863086',
    projectId: 'truediet4me-9e0f4',
    authDomain: 'truediet4me-9e0f4.firebaseapp.com',
    storageBucket: 'truediet4me-9e0f4.firebasestorage.app',
    measurementId: 'G-S9PSRH4FJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkhTuEO5w_82Sld4_m2zTc9IcJwEZPDw8',
    appId: '1:941962863086:android:0dc1e43803d6eec992aeff',
    messagingSenderId: '941962863086',
    projectId: 'truediet4me-9e0f4',
    storageBucket: 'truediet4me-9e0f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTegwREP62PHGPWtInul68qZCjjaC4v1E',
    appId: '1:941962863086:ios:a08c0487e19ef7a292aeff',
    messagingSenderId: '941962863086',
    projectId: 'truediet4me-9e0f4',
    storageBucket: 'truediet4me-9e0f4.firebasestorage.app',
    iosBundleId: 'com.example.dietitionAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTegwREP62PHGPWtInul68qZCjjaC4v1E',
    appId: '1:941962863086:ios:a08c0487e19ef7a292aeff',
    messagingSenderId: '941962863086',
    projectId: 'truediet4me-9e0f4',
    storageBucket: 'truediet4me-9e0f4.firebasestorage.app',
    iosBundleId: 'com.example.dietitionAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw0qpSAGCrEqpNdYBxtuxr0wwLqKcIfLY',
    appId: '1:941962863086:web:b64ee481e5923d3392aeff',
    messagingSenderId: '941962863086',
    projectId: 'truediet4me-9e0f4',
    authDomain: 'truediet4me-9e0f4.firebaseapp.com',
    storageBucket: 'truediet4me-9e0f4.firebasestorage.app',
    measurementId: 'G-T11TJVP1MR',
  );
}
